compartment_ocid = "ocid1.compartment.oc1..aaaaaaaaoqn77wyhkn3crracqfaqg3pyoo5243snf4dtvhroohl5sp6hd5fq"
adb_display_name = "MiPrimeraADBDemo"
adb_db_name      = "MIADBAPP"
adb_db_workload  = "OLTP"
adb_cpu_core_count = 1
adb_data_storage_size_in_tbs = 1
adb_license_model = "LICENSE_INCLUDED"
adb_db_version = "19c"
adb_is_auto_scaling_enabled = true
# adb_subnet_id = "ocid1.subnet.oc1..aaaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"