name: Ansible Execute

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible oracle.oci
      - name: Run Ansible
        run: ansible-playbook -i localhost, master.yml