# .github/workflows/ansible_exec.yml
name: Ansible Execute

on:
  push:
    branches:
      - main
    paths:
      - 'master.yml'
      - 'catalog/**.yml'
      - 'oe_01/**/vm_vars.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'master.yml'
      - 'catalog/**.yml'
      - 'oe_01/**/vm_vars.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible & OCI collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible oracle.oci

      - name: Run Ansible playbook
        run: ansible-playbook -i localhost, master.yml
